import csv
from itertools import islice

import pandas as pd
import numpy as np
import os
import json
import pickle
from collections import OrderedDict

from rdkit import Chem
import networkx as nx

from utils_test import *

import torch
from tqdm import tqdm
import gc
import time


def get_cell_feature(cellId, cell_features):
    for row in islice(cell_features, 0, None):
        if row[0] == cellId:
            return row[1:]


def atom_features(atom):
    return np.array(
        one_of_k_encoding_unk(
            atom.GetSymbol(),
            ['C', 'N', 'O', 'S', 'F', 'Si', 'P', 'Cl', 'Br', 'Mg', 'Na', 'Ca', 'Fe', 'As',
             'Al', 'I', 'B', 'V', 'K', 'Tl', 'Yb', 'Sb', 'Sn', 'Ag', 'Pd', 'Co', 'Se',
             'Ti', 'Zn', 'H', 'Li', 'Ge', 'Cu', 'Au', 'Ni', 'Cd', 'In', 'Mn', 'Zr', 'Cr',
             'Pt', 'Hg', 'Pb', 'Unknown']
        ) +
        one_of_k_encoding(atom.GetDegree(), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) +
        one_of_k_encoding_unk(atom.GetTotalNumHs(), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) +
        one_of_k_encoding_unk(atom.GetImplicitValence(), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) +
        [atom.GetIsAromatic()]
    )


def one_of_k_encoding(x, allowable_set):
    if x not in allowable_set:
        raise Exception("input {0} not in allowable set {1}:".format(x, allowable_set))
    return list(map(lambda s: x == s, allowable_set))


def one_of_k_encoding_unk(x, allowable_set):
    """Maps inputs not in the allowable set to the last element."""
    if x not in allowable_set:
        x = allowable_set[-1]
    return list(map(lambda s: x == s, allowable_set))


def smile_to_graph(smile):
    mol = Chem.MolFromSmiles(smile)

    if mol is None:
        raise ValueError(f"Invalid SMILES: {smile}")

    c_size = mol.GetNumAtoms()

    features = []
    for atom in mol.GetAtoms():
        feature = atom_features(atom)
        features.append(feature / sum(feature))

    edges = []
    for bond in mol.GetBonds():
        edges.append([bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()])

    g = nx.Graph(edges).to_directed()
    edge_index = []
    for e1, e2 in g.edges:
        edge_index.append([e1, e2])

    return c_size, features, edge_index


def load_ppi_flow_inputs():
    """
    Load PPI graph and drug seed generated by build_ppi_flow_inputs.py.
    """
    ppi_graph_path = './data/PPI_flow/ppi_graph.pt'
    drug_seed_path = './data/PPI_flow/drug_seed.pkl'

    if not os.path.exists(ppi_graph_path):
        raise FileNotFoundError(
            f"{ppi_graph_path} not found. Please run python build_ppi_flow_inputs.py first."
        )

    if not os.path.exists(drug_seed_path):
        raise FileNotFoundError(
            f"{drug_seed_path} not found. Please run python build_ppi_flow_inputs.py first."
        )

    ppi_graph = torch.load(ppi_graph_path, map_location='cpu')
    ppi_num_nodes = ppi_graph["num_nodes"]

    with open(drug_seed_path, 'rb') as f:
        drug_seed = pickle.load(f)

    print("Loaded PPI graph:", ppi_graph_path)
    print("PPI num nodes:", ppi_num_nodes)
    print("Loaded drug seed:", drug_seed_path)
    print("Drug seed count:", len(drug_seed))

    return drug_seed, ppi_num_nodes


def creat_data(datafile, cellfile):
    # =========================
    # 1. Load cell features
    # =========================
    cell_features = []
    with open(cellfile) as csvfile:
        csv_reader = csv.reader(csvfile)
        for row in csv_reader:
            cell_features.append(row)

    cell_features = np.array(cell_features)
    print('cell_features:', cell_features.shape)

    # =========================
    # 2. Load PPI seed inputs
    # =========================
    drug_seed, ppi_num_nodes = load_ppi_flow_inputs()

    # =========================
    # 3. Build molecular graph dictionary
    # =========================
    compound_iso_smiles = []
    df_smiles = pd.read_csv('./data/smiles.csv')
    compound_iso_smiles += list(df_smiles['smile'])
    compound_iso_smiles = set(compound_iso_smiles)

    smile_graph = {}
    print('compound_iso_smiles count:', len(compound_iso_smiles))

    for smile in tqdm(compound_iso_smiles, desc="Building molecular graphs"):
        g = smile_to_graph(smile)
        smile_graph[smile] = g

    # =========================
    # 4. Read synergy label file
    # =========================
    datasets = datafile
    processed_data_file_train = 'data/processed/' + datasets + '_train.pt'

    df = pd.read_csv('data/' + datasets + '.csv')

    drug1 = np.asarray(list(df['drug1']))
    drug2 = np.asarray(list(df['drug2']))
    cell = np.asarray(list(df['cell']))
    label = np.asarray(list(df['label']))

    print('开始创建数据')
    print('samples:', len(label))

    # =========================
    # 5. Create PyG dataset for drug1
    # =========================
    TestbedDataset(
        root='data',
        dataset=datafile + '_drug1',
        xd=drug1,
        xt=cell,
        xt_featrue=cell_features,
        y=label,
        smile_graph=smile_graph,
        drug_seed=drug_seed,
        ppi_num_nodes=ppi_num_nodes
    )

    # =========================
    # 6. Create PyG dataset for drug2
    # =========================
    TestbedDataset(
        root='data',
        dataset=datafile + '_drug2',
        xd=drug2,
        xt=cell,
        xt_featrue=cell_features,
        y=label,
        smile_graph=smile_graph,
        drug_seed=drug_seed,
        ppi_num_nodes=ppi_num_nodes
    )

    print('创建数据成功')
    print('preparing ', datasets + '_.pt in pytorch format!')


if __name__ == "__main__":
    cellfile = './data/new_cell_features_954.csv'

    da = ['new_labels_0_10']

    for datafile in da:
        creat_data(datafile, cellfile)

